## Title: makeCacheMatrix and cacheSolve 
## These functions allow the user to cache the inverse of a given matrix. The matrix should be constructed in R(Studio) and then inserted in this function.  

## This function generates a list based on the matrix that is provided by the user. This list will contain a chached version of the matrix that is inserted.  

makeCacheMatrix <- function(x = matrix()){
    m <- NULL
    set <- function(y){
        x <<- y
        m <<- NULL 
    }
    get <- function() x
    setInverse <- function(inverse) m <<- inverse
    getInverse <- function() m
    list(set = set, get = get, setInverse = setInverse, getInverse = getInverse)
}


## This function takes the input from the user, presumably the cached matrix that was generated by the user with the makeCacheMatrix function provided above. 
## 'm' represents the inverted matrix. The function will generate the solved cached version of the aforementioned matrix.      

cacheSolve <- function(x, ...){
    m <- x$getInverse()
    if(!is.null(m)){
        message("getting cached data")
        return(m)
    }
    data <- x$get()
    inv <- solve(data, ...)  
    x$setInverse(m)
    m
}
